# Generated by Django 4.1.13 on 2024-02-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.BigIntegerField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('mobile', models.BigIntegerField()),
            ],
        ),
    ]
